### ISSUE TITLE
hey man really sorry if that's unrelated but hear me out

### ISSUE THREAD

**Issue by vectorassembly** [2003and/KafkaSummerPractice#1]
could not find any way to contact you but I wanted to get in touch with ya, check your main scratch profile (2003 one) if that's still possible.

**Comment by vassembly** [comment]
could not find any way to contact you but I wanted to get in touch with ya, check your main scratch profile if that's still possible.

**Comment by 2003and** [comment]
Hey there! Glad to hear that! You can text me in discord if you want to, 2003and#0102, in case you don't feel uncomfortable to chat there. I also have a telegram account, @Clyde1234, so you can dm me there too. Was it something specific you wanted to do, or did you want to simply chat?
